services:
  - type: web
    name: backend-fastapi
    env: python
    buildCommand: ""
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --chdir backend/
    region: us
    plan: free
